name: 转换
on:
  push:
    branches: [main]
    paths:
      - "input/**"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: 'pypy3.10' 
      - name: 安装依赖
        run: |
          sudo apt-get install -y ffmpeg python3-pip
          pip install -r r.txt
      - name: 处理音频
        run: python main.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: output/*
      
